[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/'
]

[rpc_endpoints]
hedera_testnet = "https://testnet.hashio.io/api"
hedera_previewnet = "https://previewnet.hashio.io/api"
hedera_mainnet = "https://mainnet.hashio.io/api"